const age = 12;
console.log(age);
const name = "Vladyslav";
console.log(name);
const isStudent = true;
console.log(isStudent);
const myString = "Креативні люди правлять світом"
console.log(myString);
let myNumber = 57;
myNumber += 10;
console.log(myNumber);
const myNull = null;
console.log(myNull);
const userName = prompt("Введіть своє ім’я");
alert(userName);
console.log(typeof userName);
const userAnswer = confirm("Ви дійсно хочете покинути сторінку?");
console.log(userAnswer);
alert("Увага! Дія може бути небезпечною.");
confirm("Ви впевнені, що хочете продовжити?");